const { EmbedBuilder, AttachmentBuilder } = require("discord.js");
const mainconfig = require("../../../mainconfig.js");

module.exports = {
    name: "transcript",
    category: "Tickets",
    aliases: ["savetranscript", "ticketlog"],
    description: "Generate a transcript of the current ticket",
    run: async (client, message, args, prefix) => {
        const isOwner = message.author.id === mainconfig.BotOwnerID || 
            (mainconfig.OwnerInformation?.OwnerID || []).includes(message.author.id);
        const isAdmin = message.member.permissions.has("ADMINISTRATOR");
        const isStaff = message.member.permissions.has("ManageChannels");
        
        if (!isOwner && !isAdmin && !isStaff) {
            return message.reply({
                embeds: [new EmbedBuilder()
                    .setColor("#FF0000")
                    .setTitle("❌ Access Denied")
                    .setDescription("```You do not have permission to use this command!```")
                    .setTimestamp()
                ]
            });
        }

        if (!message.channel.name.includes("ticket")) {
            return message.reply({
                embeds: [new EmbedBuilder()
                    .setColor("#FF0000")
                    .setTitle("❌ Invalid Channel")
                    .setDescription("This command can only be used in ticket channels!")
                    .setTimestamp()
                ]
            });
        }

        const statusMsg = await message.reply({
            embeds: [new EmbedBuilder()
                .setColor("#FEE75C")
                .setTitle("⏳ Generating Transcript...")
                .setDescription("Please wait while the transcript is being created.")
            ]
        });

        try {
            const messages = await message.channel.messages.fetch({ limit: 100 });
            const sortedMessages = messages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);
            
            let transcript = `=== TICKET TRANSCRIPT ===\n`;
            transcript += `Channel: ${message.channel.name}\n`;
            transcript += `Generated: ${new Date().toLocaleString()}\n`;
            transcript += `Total Messages: ${messages.size}\n`;
            transcript += `${"=".repeat(50)}\n\n`;

            sortedMessages.forEach(msg => {
                const timestamp = new Date(msg.createdTimestamp).toLocaleString();
                transcript += `[${timestamp}] ${msg.author.tag}:\n`;
                transcript += `${msg.content || "[No text content]"}\n`;
                if (msg.attachments.size > 0) {
                    transcript += `Attachments: ${msg.attachments.map(a => a.url).join(", ")}\n`;
                }
                transcript += "\n";
            });

            const buffer = Buffer.from(transcript, 'utf-8');
            const attachment = new AttachmentBuilder(buffer, { name: `transcript-${message.channel.name}-${Date.now()}.txt` });

            await statusMsg.edit({
                embeds: [new EmbedBuilder()
                    .setColor("#00FF00")
                    .setTitle("✅ Transcript Generated")
                    .setDescription(`Transcript for **${message.channel.name}** has been created.`)
                    .addFields({ name: "📊 Stats", value: `Messages: ${messages.size}` })
                    .setFooter({ text: `Generated by ${message.author.tag}`, iconURL: message.author.displayAvatarURL({ dynamic: true }) })
                    .setTimestamp()
                ],
                files: [attachment]
            });
        } catch (error) {
            console.error("Transcript error:", error);
            statusMsg.edit({
                embeds: [new EmbedBuilder()
                    .setColor("#FF0000")
                    .setTitle("❌ Error")
                    .setDescription("Failed to generate transcript.")
                ]
            });
        }
    }
};
